Add a flag to enable grpc.
dsymonds/gotoc pull request #4
Opened 2016-09-25 19:02 UTC by sbunce

This is needed to get protoc-gen-go to output grpc code.

2016-09-25 23:06 UTC, dsymonds commented
This will need a bit of thought. You're right that this is the required mechanism on the CodeGeneratorRequest edge, but I'm not sure I want to bake this in in this form. The specific `plugins=grpc` value only works with `protoc-gen-go`, and `gotoc` is trying to be agnostic to the generated language.

`protoc` handles this by overloading the `--go_out` flag. I'm not keen to follow that precedence. Maybe this should be a --params flag instead?

2016-09-26 03:51 UTC, sbunce commented
I see your point. It does seem odd that protoc specifies plugins in the output flag value. My original solution of having a "-grpc" flag also doesn't seem quite right because we may want to specify additional plugins in the future.

I like your idea of "-params" because it allows us to specify additional plugins in the future without adding additional flags. I updated the pull request to use "-params".

No rush on this. This is an API change of sorts. Hard to change later.

2016-09-27 08:21 UTC, dsymonds requested changes

2016-09-27 08:21 UTC, dsymonds commented on main.go
> +		cgRequest.Parameter = proto.String("plugins="+*params)
This should pass the flag value through unmodified.

```go
cgRequest.Parameter = params
```

2016-09-27 08:21 UTC, dsymonds commented on main.go
> +	params         = flag.String("params", "", "Parameters (comma separated values) to provide to the code generator.")
"Parameters to pass to the code generator plugin (plugin-specific format)."

2016-09-27 15:15 UTC, sbunce commented on main.go
> +	params         = flag.String("params", "", "Parameters (comma separated values) to provide to the code generator.")
Done.

2016-09-27 15:15 UTC, sbunce commented on main.go
> +		cgRequest.Parameter = proto.String("plugins="+*params)
Done.

2016-09-27 15:22 UTC, sbunce commented
I kept looking at things in an overly-specific way. "-grpc", then "plugins=". Passing the raw parameters does seem like the best way to go. Thanks!

Updated the pull request.

2016-09-28 04:37 UTC, dsymonds commented
Merged in 0071f33. Thanks!

2016-09-28 04:37 UTC, closed without merging